select name from doctor; 
select date from laboratory;
select name, phone from doctor;
select * from doctor;
select name from doctor order by Name;
select name from doctor order by Name desc;
select name,disease  from patient order by  name desc,   disease desc;
select Name, age from doctor where age<35;
select * from doctor where gender="male";
select * from doctor where gender="fe" and age<30;
SELECT * from patient where date_entry BETWEEN 2020-05-25  and 2020-06-03 ;
select * from doctor where  name like '%an' order by Name ;
select *, max(doc_charge) from bill;
SELECT * from patient where disease="Heart attack"  or  age>55;
select * from patient where Doc_ID is null ;
SELECT *, MIN (doc_charge) FROM bill;
select * FROM doctor order by age desc limit 3;
select  sum(doc_charge) from bill;
select avg(age)from doctor;
select count(*) from doctor;
select * from patient where Doc_ID   in (select Doc_ID from doctor ); 
select * FROM bill where Patient_ID in (select Patient_ID from patient  where disease="heart attack");
select * from patient where Doc_ID   in (select Doc_ID from doctor  where address="Aswan"); 
SELECT status, COUNT(*) FROM room GROUP BY status;
SELECT status, COUNT(*) FROM room GROUP BY status ORDER BY 2 ;
SELECT Patient_ID,doctor.Name,patient.name FROM patient INNER JOIN doctor ON doctor.Doc_ID=patient.Doc_ID;
SELECT * FROM patient left join doctor ON patient.Patient_ID=doctor.Doc_ID ORDER BY patient.name;
SELECT * FROM patient right JOIN doctor ON patient.Patient_ID=doctor.Doc_ID ORDER BY patient.name;
select patient.name,patient.date_entry from patient natural join doctor;
select bill.num_days,receptionist.hours_work from bill cross join receptionist;